// Generated by CoffeeScript 1.6.2
(function() {
  var checkRoutes, config, e, fs, http, matchRoute, onRequest, path, projectPath, respond404, respondWithFile, url;

  http = require("http");

  url = require("url");

  fs = require("fs");

  path = require("path");

  onRequest = function(request, response) {
    var pathname;

    pathname = url.parse(request.url).pathname;
    response.writeHead(200, {
      "Content-Type": "text/plain"
    });
    return fs.stat(projectPath + config.base + pathname, function(err, stat) {
      if (!err && stat.isFile()) {
        return respondWithFile(pathname, response);
      } else {
        if (!err) {
          return fs.exists(projectPath + config.base + pathname + "/" + config.indexFile, function(err, file) {
            if (err) {
              return respondWithFile(pathname + "/" + config.indexFile, response);
            } else {
              return checkRoutes(pathname, response);
            }
          });
        } else {
          return checkRoutes(pathname, response);
        }
      }
    });
  };

  respondWithFile = function(filePath, response) {
    return fs.readFile(projectPath + config.base + filePath, "binary", function(err, file) {
      var fileExtension, mimeType;

      if (err) {
        response.writeHead(500, {
          "Content-Type": "text/plain"
        });
        response.write(err + "\n");
        response.end();
        return;
      }
      fileExtension = filePath.substr(filePath.lastIndexOf(".") + 1);
      mimeType = config.mimeTypes[fileExtension];
      if (mimeType != null) {
        response.writeHead(200, {
          "Content-Type": mimeType
        });
      }
      response.write(file, "binary");
      return response.end();
    });
  };

  checkRoutes = function(pathname, response) {
    var f, r, _ref;

    _ref = config.routes;
    for (r in _ref) {
      f = _ref[r];
      if (matchRoute(r, pathname)) {
        respondWithFile(f, response);
        return;
      }
    }
    return respond404(response);
  };

  matchRoute = function(route, pathname) {
    if (route === pathname) {
      return true;
    }
    if (route.indexOf("*") !== -1) {
      if (pathname.indexOf(route.split("*")[0]) === 0) {
        return true;
      }
    }
    return false;
  };

  respond404 = function(response) {
    response.writeHead(404, {
      "Content-Type": "text/plain"
    });
    response.write("404 Not Found\n");
    return response.end();
  };

  projectPath = process.argv[2] || "./";

  try {
    config = JSON.parse(fs.readFileSync(projectPath + "stouter_config.json", "utf8"));
  } catch (_error) {
    e = _error;
    console.log("Failed to load stouter_config.json");
    console.log("For more info on config files see https://github.com/roddeh/stouter");
    console.log(e.message);
    process.exit(1);
  }

  http.createServer(onRequest).listen(config.port);

  console.log("---------------------------");

  console.log("Started Stouter on port " + config.port);

  console.log("---------------------------");

}).call(this);
